version: "3.8"
services:
  web:
    build: .  # Tells Docker Compose to build the image using the Dockerfile in the current directory
    #user: "33:33"
    container_name: matimeclock-server
    ports:
      - "8000:80"  # Expose port 80 inside the container as port 8000 on the host
    volumes:
      #- .:/var/www/html  # Mount the current directory to /var/www/html inside the container <FIX THIS LATER!>
      #- ./db.sqlite3:/var/www/html/db.sqlite3
      - ./data:/var/www/html/data
      - ./site-config.conf:/etc/apache2/sites-available/000-default.conf  # Mounts the config file directly
