# Generated by Django 5.0.3 on 2024-03-30 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('pin', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('manager', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=19)),
                ('end_time', models.TimeField(max_length=19)),
                ('pin', models.ForeignKey(db_column='pin', on_delete=django.db.models.deletion.CASCADE, to='timeclock.employee')),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='timeclock.job')),
            ],
        ),
    ]
