# Generated by Django 5.0.3 on 2024-04-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hours',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
